(("3 Miles SW Bear" :latitude 39.55 :longitude -75.72 :interesting-place "Lum's Pond")
 ("3 Miles NW Bear" :latitude  39.62 :longitude -75.71 :interesting-place "Glasgow Park")
 ("Newark South" :latitude 39.67 :longitude -75.76 :interesting-place "Star Campus")
 ("Newark North" :latitude 39.69 :longitude -75.76 :interesting-place "Main Campus")
 ("3 Miles N Newark" :latitude 39.71 :longitude -75.75 :interesting-place "Deerfield and White Clay Creek")
 ("Pike Creek" :latitude 39.73 :longitude -75.69 :interesting-place "Carousel Farm Park")
 ("2 Miles SW Hockessin" :latitude 39.77 :longitude -75.71 :interesting-place "Woodside Farm Creamery")
 ("3 Miles S Stanton" :latitude 39.68 :longitude -75.64 :interesting-place "Christiana Mall")
 ("Wilmington, New Castle County Airport" :latitude 39.67 :longitude -75.62 :interesting-place "New Castle Airport")
 ("Bellefonte" :latitude 39.77 :longitude -75.51 :interesting-place "Bellevue State Park"))
